changelog:
  categories:
    - title: 🚀 New Features
      labels:
        - enhancements
    - title: 🐞 Bug Fixes
      labels:
        - bug
    - title: ✨ Improvements
      labels:
        - '*'
      exclude:
        labels:
          - enhancements
          - bug
          - documentation
    - title: 📖 Documentation
      labels:
        - documentation
