version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      - conda env update --name ${READTHEDOCS_VERSION} --file ecodata-dev-env.yml
      - conda list

conda:
 environment: ecodata-env.yml

# Build all downloadable formats
formats: all