version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
    - conda list

conda:
  environment: pymovebank-dev-env.yml

# Build all downloadable formats
formats: all