name: pmv
channels:
- pyviz
- conda-forge
- defaults
dependencies:
- python=3.9
- cartopy
- geopandas
- matplotlib
- pandas
- shapely<1.8.2
- xarray
- dask
- netCDF4
- bottleneck
- cfgrib
- rasterio
- conda-forge::rioxarray
- pyviz::hvplot
- pyviz::panel
- pyviz::datashader
- pyviz::geoviews
- conda-forge::geocube
- dataprep
- conda-forge::ffmpeg
- anaconda::git
- conda-forge::gdown
- pip
- pip:
    - awesome-panel-extensions==20221019.2