[tool.isort]
profile = "black"
multi_line_output = 3
skip_glob = ["*env*/*"]


[tool.black]
line-length = 120
experimental-string-processing = true
# This is a regular expression (hence the \. is escaping the ., and not a literal \.)
exclude = '''
(
    /(\.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | .*env.*
    | _build
    | buck-out
    | build
    | dist
    | docs/*
    )
)
'''