on:
  push:
    # Sequence of patterns matched against refs/tags
#    tags:  # TODO uncomment after testing
#        - v*
jobs:
  build:
    name: ECODATA-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ARCH: x86_64
            TARGET_PLATFORM: win-64
            OS_NAME: "Windows"

          - os: macos-latest
            ARCH: arm64
            TARGET_PLATFORM: osx-arm64
            OS_NAME: "MacOSX"

          - os: macos-latest
            ARCH: x86_64
            TARGET_PLATFORM: osx-64
            OS_NAME: "MacOSX"

          - os: ubuntu-latest
            ARCH: x86_64
            TARGET_PLATFORM: linux-64
            DOCKER_ARCH: amd64
            DOCKERIMAGE: condaforge/linux-anvil-comp7
            OS_NAME: "Linux"

    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - uses: conda-incubator/setup-miniconda@v2.2.0
          with:
            miniforge-version: "latest"
            miniforge-variant: Mambaforge
            use-mamba: true

        - name: Run conda constructor
          run: |
              conda install constructor -c conda-forge
              cd scripts
              constructor .

        - name: upload artifacts
          uses: actions/upload-artifact@v3
          with:
            path: build/ECODATA-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}*
            name: ECODATA-${{ matrix.OS_NAME }}-${{ matrix.ARCH }}