name: Pages
on:
  pull_request:
    branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Make conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: pmv-dev
        environment-file: ./pymovebank-dev-env.yml
        use-mamba: true
    - name: Running the Sphinx to gh-pages Action
      uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.2
      with:
        branch: develop
        dir_docs: docs
        sphinxopts: ''
