name: Pages
on:
  push:
    branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('etc/example-environment.yml') }}
    - name: Make conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pmv-dev
        environment-file: ./pymovebank-dev-env.yml
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
    - name: Running the Sphinx to gh-pages Action
      uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.2
      with:
        branch: develop
        dir_docs: docs
        sphinxopts: ''
